"""
Django settings for tasktracker project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from environment; fail in prod if missing; use unsafe dev fallback otherwise
from django.core.exceptions import ImproperlyConfigured
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY and os.getenv("APP_ENV", "prod") != "dev":
    raise ImproperlyConfigured("SECRET_KEY manquante en production")
SECRET_KEY = SECRET_KEY or "dev-unsafe-secret-key-change-me"

# SECURITY WARNING: don't run with debug turned on in production!
APP_ENV = os.getenv("APP_ENV", "prod")
DEBUG = APP_ENV == "dev"

# Pour le développement local, on autorise toutes les origines ( ne pas faire en production)
if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS","tomremili.fr,www.tomremili.fr,tasktracker.tomremili.fr").split(",")
    CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS","https://tomremili.fr,https://www.tomremili.fr,https://tasktracker.tomremili.fr").split(",")
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT","true").lower() in ("1","true","yes","on")
    if os.getenv("USE_X_FORWARDED_PROTO","1").lower() in ("1","true","yes","on"):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO','https')


# Application definition

INSTALLED_APPS = [
    # Exemple d'import des models
    'tasks.apps.TasksConfig',
    'auth.apps.AuthConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

#if DEBUG:  # en dev uniquement
    #INSTALLED_APPS += ["django.contrib.admin"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tasktracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tasktracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "tasktracker"),
        "USER": os.getenv("POSTGRES_USER", "taskuser"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "taskpass"),
        "HOST": os.getenv("POSTGRES_HOST", "db"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration des URLs d'authentification
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/tasks/' # Redirige vers la liste des tâches
LOGOUT_REDIRECT_URL = '/auth/login/'
